### ISSUE TITLE
How to download the sp1s_aa_1000Hz_test.mat file?

### ISSUE THREAD

**Issue by badshihi** [kevinchangwang/EEG_Classify#1]
Hi, Wang, it's very helpful to read your code about EEG classification, but I want to run the code, the file sp1s_aa_1000Hz_test.mat is missing, and I couldn't find it online. Could you tell me where the download the data please? Thank you!

**Comment by GitHubxiuwen** [comment]
HI,I have a same problem with you,badshihi.Do you get the data,now?
Hi,kevinchangwang,can you open the link to the data?Thank you,again!

**Comment by badshihi** [comment]
@GitHubxiuwen I've found one set similar to the wanted dataset, and I found an obvious flaw in wang's code.

**Comment by huangenkuo** [comment]
Could you tell me where the download the data please? Thank you!

**Comment by badshihi** [comment]
@huangenkuo I can't hardly remember the source, but you can google the file name. And there are some flaw in it maybe.

**Comment by kevinchangwang** [comment]
The data is from the BCI competition. I used dataset IV from the 2nd competition. You need to provide your name and email to download the sets. 

http://www.bbci.de/competition/ii/

This code is pretty old and may not work with current versions of Keras. There were some API changes shortly after I wrote this code. Please let me know what the error consists of so that I can make necessary changes. @badshihi
